import LegalPage from "@/components/LegalPage";

export default function Privacy() {
  return <LegalPage titolo="Privacy Policy" sezioni={[
    { h: "1. Titolare del trattamento", p: "Il titolare del trattamento dei dati personali raccolti tramite il sito nutriforce.it è NutriForce S.r.l., con sede legale in Via Nizza 230, 10126 Torino, P.IVA IT09384720117. Il titolare può essere contattato all'indirizzo email privacy@nutriforce.it per qualsiasi richiesta relativa al trattamento dei dati personali. La presente informativa è resa ai sensi degli articoli 13 e 14 del Regolamento UE 2016/679 (GDPR) e descrive le modalità con cui raccogliamo, utilizziamo e proteggiamo i dati personali degli utenti che visitano il nostro sito o effettuano acquisti tramite la piattaforma." },
    { h: "2. Tipologie di dati raccolti", p: ["Raccogliamo diverse tipologie di dati personali in funzione delle interazioni che l'utente ha con il sito. I dati di navigazione comprendono indirizzo IP, tipo di browser, sistema operativo, pagine visitate, tempo di permanenza e provenienza del visitatore. Questi dati sono raccolti in forma aggregata per finalità statistiche e di sicurezza.", "I dati forniti volontariamente dall'utente includono nome, cognome, indirizzo email, indirizzo di spedizione e fatturazione, numero di telefono e dati di pagamento. Questi dati sono raccolti esclusivamente quando l'utente effettua un ordine, si iscrive alla newsletter, compila il form di contatto o crea un account."] },
    { h: "3. Finalità del trattamento", p: "I dati personali vengono trattati per le seguenti finalità: gestione degli ordini e della spedizione dei prodotti acquistati; adempimento di obblighi contrattuali, fiscali e contabili; invio di comunicazioni commerciali (solo previo consenso); risposta alle richieste di assistenza inviate tramite il form contatti; analisi statistiche aggregate per il miglioramento del servizio; prevenzione di frodi e attività illecite." },
    { h: "4. Base giuridica", p: "Il trattamento si fonda su diverse basi giuridiche a seconda della finalità: l'esecuzione del contratto per la gestione degli ordini, l'obbligo legale per gli adempimenti fiscali e contabili, il legittimo interesse del titolare per le finalità di sicurezza e prevenzione frodi, il consenso esplicito dell'interessato per l'invio di comunicazioni commerciali e la profilazione." },
    { h: "5. Modalità del trattamento", p: "Il trattamento dei dati personali avviene mediante strumenti informatici e telematici, con modalità organizzative e logiche strettamente correlate alle finalità indicate. Adottiamo misure di sicurezza tecniche e organizzative adeguate a garantire la riservatezza, l'integrità e la disponibilità dei dati, includendo crittografia delle comunicazioni, accesso limitato ai soli soggetti autorizzati, backup periodici e procedure di disaster recovery." },
    { h: "6. Conservazione dei dati", p: "I dati personali sono conservati per il tempo strettamente necessario al raggiungimento delle finalità per cui sono stati raccolti. I dati relativi agli ordini sono conservati per dieci anni come previsto dalla normativa fiscale italiana. I dati raccolti per finalità di marketing sono conservati fino alla revoca del consenso da parte dell'interessato. I dati di navigazione vengono conservati per un massimo di ventiquattro mesi." },
    { h: "7. Comunicazione e diffusione", p: "I dati personali possono essere comunicati a terzi solo per le finalità sopra indicate e nei limiti strettamente necessari. I principali destinatari sono: corrieri per la spedizione degli ordini, istituti di pagamento per la gestione delle transazioni, fornitori di servizi cloud e di posta elettronica, consulenti fiscali e contabili. Tutti i destinatari sono vincolati da specifici accordi sulla protezione dei dati. I dati non vengono trasferiti al di fuori dello Spazio Economico Europeo." },
    { h: "8. Diritti dell'interessato", p: "Ai sensi del GDPR, l'utente ha diritto di accedere ai propri dati personali, richiederne la rettifica o la cancellazione, ottenere la limitazione del trattamento, opporsi al trattamento, ricevere i propri dati in formato strutturato (portabilità) e revocare in qualsiasi momento il consenso prestato. Per esercitare questi diritti è sufficiente scrivere a privacy@nutriforce.it. L'utente ha inoltre il diritto di proporre reclamo all'Autorità Garante per la protezione dei dati personali." },
    { h: "9. Modifiche all'informativa", p: "La presente informativa può essere aggiornata in qualsiasi momento. Gli utenti registrati saranno informati delle modifiche sostanziali via email. La data dell'ultimo aggiornamento è indicata in cima al documento." },
  ]} />;
}
