import LegalPage from "@/components/LegalPage";

export default function Termini() {
  return <LegalPage titolo="Termini e Condizioni di Vendita" sezioni={[
    { h: "1. Premessa e ambito di applicazione", p: "I presenti termini e condizioni generali di vendita disciplinano l'acquisto di prodotti effettuato a distanza tramite rete telematica sul sito nutriforce.it, di proprietà di NutriForce S.r.l., con sede legale in Via Nizza 230, 10126 Torino, P.IVA IT09384720117. Tutti i contratti di vendita conclusi tramite il sito tra NutriForce e il cliente saranno regolati dalle presenti condizioni e dalla normativa italiana applicabile, in particolare dal D.Lgs. 206/2005 (Codice del Consumo) e dal D.Lgs. 70/2003 in materia di commercio elettronico." },
    { h: "2. Prodotti e disponibilità", p: "I prodotti offerti in vendita sul sito sono integratori alimentari conformi alla normativa italiana ed europea vigente. Tutti i prodotti sono notificati al Ministero della Salute e prodotti in stabilimenti certificati ISO 22000. Le immagini e le descrizioni dei prodotti hanno valore puramente illustrativo e non costituiscono elemento essenziale del contratto. La disponibilità dei prodotti è soggetta a verifica al momento dell'ordine: in caso di indisponibilità sopravvenuta il cliente sarà tempestivamente informato e avrà diritto al rimborso integrale delle somme eventualmente già corrisposte." },
    { h: "3. Conclusione del contratto", p: "Il contratto stipulato tra NutriForce e il cliente deve intendersi concluso con la conferma dell'ordine inviata per posta elettronica all'indirizzo indicato dal cliente. La conferma dell'ordine include il riepilogo dei prodotti acquistati, il prezzo, le modalità di pagamento, i tempi e i costi di spedizione e i dati di fatturazione. Si invita il cliente a stampare e conservare la conferma dell'ordine per i successivi adempimenti." },
    { h: "4. Prezzi e modalità di pagamento", p: "Tutti i prezzi indicati sul sito sono espressi in euro e si intendono comprensivi di IVA e di ogni altra imposta applicabile. I costi di spedizione sono indicati separatamente e calcolati in base al peso dell'ordine e alla destinazione. Il pagamento può essere effettuato tramite carta di credito, PayPal, bonifico bancario anticipato o contrassegno (con sovrapprezzo). Tutte le transazioni avvengono su circuiti protetti e i dati di pagamento non sono mai memorizzati sui nostri server." },
    { h: "5. Spedizione e consegna", p: "I prodotti vengono spediti entro ventiquattro ore lavorative dalla conferma del pagamento, dal lunedì al venerdì. La consegna avviene tramite corriere espresso entro due o tre giorni lavorativi dalla spedizione per l'Italia continentale, mentre per le isole maggiori i tempi possono estendersi fino a cinque giorni. La spedizione è gratuita per ordini superiori a cinquanta euro; per ordini di importo inferiore si applica un contributo spese di sei euro e novanta centesimi." },
    { h: "6. Diritto di recesso", p: "Ai sensi degli articoli 52 e seguenti del Codice del Consumo, il cliente consumatore ha diritto di recedere dal contratto, senza alcuna penalità e senza specificarne il motivo, entro quattordici giorni lavorativi dalla data di ricevimento dei prodotti. Per esercitare il recesso il cliente deve inviare una comunicazione scritta a recesso@nutriforce.it indicando i prodotti per i quali intende recedere e i propri dati. I prodotti devono essere restituiti integri, non utilizzati, nella confezione originale sigillata. Le spese di restituzione sono a carico del cliente. Il rimborso verrà effettuato entro quattordici giorni dal ricevimento dei prodotti restituiti." },
    { h: "7. Garanzia legale di conformità", p: "Tutti i prodotti venduti tramite il sito sono coperti dalla garanzia legale di conformità prevista dagli articoli 128 e seguenti del Codice del Consumo. In caso di difetto di conformità il cliente ha diritto al ripristino della conformità, alla riduzione del prezzo o alla risoluzione del contratto. La garanzia ha durata di ventiquattro mesi dalla consegna del prodotto. I difetti devono essere denunciati entro due mesi dalla scoperta scrivendo a info@nutriforce.it." },
    { h: "8. Reclami e assistenza", p: "Per qualsiasi reclamo o richiesta di assistenza il cliente può contattare il servizio clienti scrivendo a info@nutriforce.it o telefonando al numero +39 011 1234567 dal lunedì al venerdì, dalle 9 alle 18. Ci impegniamo a rispondere a tutti i reclami entro cinque giorni lavorativi dalla ricezione." },
    { h: "9. Legge applicabile e foro competente", p: "Il presente contratto è regolato dalla legge italiana. Per qualsiasi controversia relativa all'interpretazione, esecuzione e risoluzione del presente contratto sarà competente il foro del luogo di residenza o domicilio del consumatore se ubicato in Italia, in via inderogabile. Per le controversie tra professionisti sarà competente in via esclusiva il Foro di Torino. Il cliente consumatore può inoltre avvalersi della piattaforma europea di risoluzione delle controversie online disponibile sul sito della Commissione Europea." },
  ]} />;
}
